### ISSUE TITLE
Automated updates?

### ISSUE THREAD

**Issue by Boshen** [wooorm/npm-high-impact#2]
This hasn't been updated for a while, I'm getting packages that are removed from npm.

**Comment by wooorm** [comment]
Hi! I update it every 3 months. It takes 2 days to crawl the ecosystem and it breaks, I don’t think that can be automated. I am crawling it right now, anyway.

**Comment by voxpelli** [comment]
I have automated some similar and constructed https://github.com/voxpelli/list-dependents-cli – is based on ecosyste.ms

**Comment by wooorm** [comment]
How is that similar, or related to this question? 🤔 To be clear: this build needs to get current download counts for 5million + packages. I don’t think there’s another provider for that data other than npm

**Comment by voxpelli** [comment]
https://github.com/ecosyste-ms/packages has that data: https://packages.ecosyste.ms/registries/npmjs.org/packages?order=desc&sort=downloads

See https://github.com/neostandard/neostandard/blob/main/dependents-data/source/standard.ndjson, https://github.com/neostandard/neostandard/pull/168, https://github.com/neostandard/neostandard/blob/main/.github/workflows/sync-update.yml and https://github.com/neostandard/neostandard/blob/main/.github/workflows/sync-reusable.yml for how I use it to eg. list the most downloaded dependents of `standard`

**Comment by wooorm** [comment]
OK, but npm has the data too; how do you known/why do you think asking ecosyste-ms about 5 million packages will be faster?

**Comment by wooorm** [comment]
I see links to 50 files of changed files but I am a bit lost — do you have a link that shows how you get data from that source?

**Comment by voxpelli** [comment]
Here's how I'm fetching: https://github.com/voxpelli/list-dependents/blob/0d40d49601aaf8a5eaf447860da561310caf504e/lib/ecosystems.js#L89

Here's their API docs: https://packages.ecosyste.ms/docs/index.html

`ecosyste.ms` is the spiritual successor to `libraries.io`

**Comment by wooorm** [comment]
thanks!
- librariesio is also used here
- still, my question: why do you think sending 5 million requests to ecosystems is better than sending them to npm

**Comment by andrew** [comment]
@wooorm I could potentially write a database query and an api endpoint for you to help avoid making all those requests?

**Comment by voxpelli** [comment]
It may be that @andrew can suggest a better way of pulling this amount of data, but this would be the base of it:

![Skärmavbild 2024-11-25 kl  15 53 27](https://github.com/user-attachments/assets/1c40c6ac-7697-453b-94bf-667ae7018fbe)

**Comment by andrew** [comment]
Yeah, then page through, you can see the next and previous links in the headers:

```
...
etag: W/"b1c75e14ccd6b433b571b84a98393259"
last-modified: Mon, 25 Nov 2024 06:08:36 GMT
link: <https://packages.ecosyste.ms/api/v1/registries/npmjs.org/packages?order=asc&sort=latest_release_published_at&page=1&per_page=100>; rel="first", <https://packages.ecosyste.ms/api/v1/registries/npmjs.org/packages?order=asc&sort=latest_release_published_at&page=2&per_page=100>; rel="next"
nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
page-items: 100
referrer-policy: strict-origin-when-cross-origin
...
```

**Comment by voxpelli** [comment]
And I would be happy to extend https://github.com/voxpelli/list-dependents/blob/0d40d49601aaf8a5eaf447860da561310caf504e/lib/ecosystems.js#L89 to facilitate that

**Comment by andrew** [comment]
I also have a `critical` parameter that I use to highlight the very most used accounts, that accounts for 80% of all downloads and dependents for the given registry, for npm that's about 2,300 packages.

**Comment by wooorm** [comment]
Hi!

I worry about accuracy and using a “man in the middle”.
With npm I know it’s accurate and online and will be for years to come.
I personally think it’s fine to not update this package all the time. The “top” packages don’t change daily (and if they fluctuate around the cut-off at the bottom it’s IMO not that interesting).

My main Qs boil down to:

- how accurate is ecosyste-ms? how recent is the data, how often do you get it from npm? are numbers rounded? If I remember correctly librariesio had non-recent download counts (or missing?), and it is sometimes buggy (forks of webpack seen as webpack itself, is noted here in the readme)

- what’s the plan with ecosyste-ms, how many years will it be maintained? as in, librariesio sometimes went down I believe and it is now sold to tidelift?

As for what is needed, it’s not too complex, the 2 criteria are in the readme: https://github.com/wooorm/npm-high-impact#what-is-this. The scripts section explains how it all works and the limitations of npm.
Regardless of my opinions and this package, the 2 endpoints for those 2 criteria are probably good to have on ecosyste-ms, and useful to other folks?
Say 100 packages per page, that could then be crawled in 100 or 200 HTTP requests!

**Comment by andrew** [comment]
> Say 100 packages per page, that could then be crawled in 100 or 200 HTTP requests!

you can do a max of 1000 packages per page

I aim to sync every npm package at least every month, even if it has no releases, for top packages they are synced much more frequently.

The project is supported by Open Source Collective, Socket.dev, Snyk and others and is hopefully going to stick around for a long time, currently serving up 733 million requests per month!

**Comment by wooorm** [comment]
Cool! Thanks for the info. I think i’ll investigate it next time.

Note to myself in 3 months: compare results of both methods.

**Comment by wooorm** [comment]
@Boshen To get back to the original question, “I'm getting packages that are removed from npm.” Yes, that is expected, even with latest data I just published; folks are gaming these numbers and uploading dangerous things that npm takes down
